# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1364883867);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1364901694);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.migration.version", 7);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.buildID", "20130307074601");
user_pref("browser.startup.homepage_override.mstone", "17.0.4");
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:17.0.4");
user_pref("extensions.firebug.externalEditors", "Aptana");
user_pref("extensions.firebug.externalEditors.Aptana.executable", "C:\\Users\\NGA1HC\\AppData\\Local\\Aptana Studio 3\\AptanaStudio3.exe");
user_pref("extensions.firebug.externalEditors.Aptana.label", "Aptana Studio");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"ccep1.metasearch@de.bosch.com\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\extensions\\\\ccep1.metasearch@de.bosch.com\",\"mtime\":1342750605018},\"{1BC9BA34-1EED-42ca-A505-6D2F1A935BBB}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\extensions\\\\{1BC9BA34-1EED-42ca-A505-6D2F1A935BBB}\",\"mtime\":1336723545007},\"{25A1388B-6B18-46c3-BEBA-A81915D0DE8F}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\extensions\\\\{25A1388B-6B18-46c3-BEBA-A81915D0DE8F}.xpi\",\"mtime\":1330922276000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1363139248332},\"{CAFEEFAC-0016-0000-0041-ABCDEFFEDCBA}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\extensions\\\\{CAFEEFAC-0016-0000-0041-ABCDEFFEDCBA}\",\"mtime\":1364177707262}}}]");
user_pref("extensions.lastAppVersion", "17.0.4");
user_pref("extensions.lastPlatformVersion", "17.0.4");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gfx.direct3d.prefer_10_1", true);
user_pref("intl.charsetmenu.browser.cache", "UTF-8, ISO-8859-1");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 104439);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1364956375);
user_pref("toolkit.telemetry.prompted", 2);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1367475870);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
